<a href="https://colab.research.google.com/github/barsha0518/barsha-_ML_1st_lab_assignment/blob/main/barsha_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION NO.1

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
res = np.flip(arr)
print("final array", str(res))

final array [5 4 6 3 2 1]


In [ ]:
import numpy as np
array1=np.array([[1,2,3],[2,4,5],[1,2,3]])
flat_arr = array1.flatten()
print(flat_arr)

[1 2 3 2 4 5 1 2 3]


In [ ]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
comparison = arr1 == arr2
equal_arrays = comparison.all()
print(equal_arrays)



True


In [ ]:
import numpy as np
x= np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())



Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [ ]:
import numpy as np
y=np.array([1,1,1,2,3,4,22,4,3,3])
print("Original array:")
print(y)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[ 1  1  1  2  3  4 22  4  3  3]
Most frequent value in the above array:
1


In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = np.sum(gfg)

sum_row_wise = np.sum(gfg, axis=1)

sum_column_wise = np.sum(gfg, axis=0)

sum_all_elements, sum_row_wise, sum_column_wise


(45,
 matrix([[14],
         [16],
         [15]]),
 matrix([[20,  9, 16]]))

In [ ]:
import numpy as np
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
trace = np.trace(n_array)


print("sum of diagonal elements of given  matrix:")
print(trace)
w, v = np.linalg.eig(n_array)

print("Printing the Eigen values of the given square array:\n",
      w)

print("Printing Right eigenvectors of the given square array:\n",
      v)
print("inverse of the matrix",np.linalg.inv(n_array))
det = np.linalg.det(n_array)

print("\nDeterminant of given  matrix:")
print(int(det))

sum of diagonal elements of given  matrix:
176
Printing the Eigen values of the given square array:
 [98.16835147 28.097044   49.73460452]
Printing Right eigenvectors of the given square array:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse of the matrix [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

Determinant of given  matrix:
137180


In [ ]:
import numpy as np
p = [[1,2],[2,3]]
q=[[4,5],[6,7]]
res = np.dot(p,q)
print(res)
print("convaruance",np.cov(p, q))

[[16 19]
 [26 31]]
convaruance [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
import numpy as np
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
res = np.dot(p,q)
print(res)
print("convaruance",np.cov(p, q))



[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nInner product of matrices x and y =")
print(np.inner(x, y))
print("\nOuter product of matrices x and y =")
print(np.outer(x, y))
print("\nCross product of matrices x and y =")
print(np.cross(x, y))


Inner product of matrices x and y =
[[17 52]
 [13 62]]

Outer product of matrices x and y =
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cross product of matrices x and y =
[[-20   4   7]
 [-84  36  20]]


ques 2

In [ ]:
import numpy as np


array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_array = np.abs(array)


flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])

percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)

percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)


mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)


print("Element-wise absolute value:\n", abs_array)

print("Percentiles of flattened array (25th, 50th, 75th):", percentiles_flattened)
print("Percentiles for each column (25th, 50th, 75th):\n", percentiles_columns)
print("Percentiles for each row (25th, 50th, 75th):\n", percentiles_rows)

print("Mean, Median, Standard Deviation of flattened array:")
print("Mean:", mean_flattened)
print("Median:", median_flattened)
print("Standard Deviation:", std_flattened)

print("Median, Standard Deviation for each column:")
print("Mean:", mean_columns)
print("Median:", median_columns)
print("Standard Deviation:", std_columns)

print("Median, Standard Deviation for each row:")
print("Mean:", mean_rows)
print("Median:", median_rows)
print("Standard Deviation:", std_rows)


i. Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]

ii. Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]
Percentiles for each column (25th, 50th, 75th):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row (25th, 50th, 75th):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

iii. Mean, Median, Standard Deviation of flattened array:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Mean, Median, Standard Deviation for each column:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Mean, Median, Standard Deviation for each row:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


In [ ]:
import numpy as np
a= np.array([-1.8,-1.6,-0.5,1.6,1.8,3.0])
floor_values= np.floor(a)
print("floor value",floor_values)
ceiling_value = np.ceil(a)
print("ceiling value",ceiling_value)
truncated_value= np.trunc(a)
print("truncated value",truncated_value)
rounded_values= np.round(a)
print("rounded value",rounded_values)

floor value [-2. -2. -1.  1.  1.  3.]
ceiling value [-1. -1. -0.  2.  2.  3.]
truncated value [-1. -1. -0.  1.  1.  3.]
rounded value [-2. -2. -0.  2.  2.  3.]


QUES 3

In [ ]:
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)
sorted_array = np.sort(array)
print(" Sorted array:", sorted_array)

sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

four_smallest = np.partition(array, 4)[:4]
four_smallest_sorted = np.sort(four_smallest)
print("Four smallest values:", four_smallest_sorted)

five_largest = np.partition(array, -5)[-5:]
five_largest_sorted = np.sort(five_largest)[::-1]
print("Five largest values:", five_largest_sorted)



[ 10  52  62  16  16  54 453]
 Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
Four smallest values: [10 16 16 52]
Five largest values: [453  62  54  52  16]


In [ ]:
import numpy as np
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print(array)
integer_elements = array[array == np.floor(array)]
float_elements = array[array != np.floor(array)]
print("i. Integer elements only:", integer_elements)
print("ii. Float elements only:", float_elements)


[1.  1.2 2.2 2.  3.  2. ]
i. Integer elements only: [1. 2. 3. 2.]
ii. Float elements only: [1.2 2.2]


QUES 4

In [ ]:
import numpy as np

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import os

def img_to_array(path):
    try:
        # Load the image
        img = Image.open(path)

        # Convert the image to a NumPy array
        img_array = np.array(img)

        # Determine the file name for the text file
        text_file_path = path.rsplit('.', 1)[0] + '.txt'

        # Check if the image is grayscale or RGB
        if len(img_array.shape) == 2:  # Grayscale image
            # Save grayscale image array to text file
            np.savetxt(text_file_path, img_array, fmt='%d')
        elif len(img_array.shape) == 3 and img_array.shape[2] == 3:  # RGB image
            # Save RGB image array to text file
            np.savetxt(text_file_path, img_array.reshape(-1, 3), fmt='%d')
        else:
            raise ValueError("Unsupported image format")

        print(f"Image array saved to {text_file_path}")
        return text_file_path
    except FileNotFoundError:
        print(f"File not found: {path}")
    except IOError as e:
        print(f"IOError: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")
def load_and_display_image(text_file_path):
    try:

        img_array = np.genfromtxt(text_file_path, dtype=int)

        if img_array.ndim == 2:
            plt.imshow(img_array, cmap='gray')
        elif img_array.ndim == 1 and img_array.size % 3 == 0:
            height = int(np.sqrt(img_array.size // 3))
            img_array = img_array.reshape((height, height, 3))
            plt.imshow(img_array)
        else:
            raise ValueError("Unsupported image format or text file contents")

        plt.axis('off')
        plt.show()
    except FileNotFoundError:
        print(f"File not found: {text_file_path}")
    except IOError as e:
        print(f"IOError: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")


image_path = 'path_to_your_image.jpg'
text_file_path = img_to_array(image_path)
if text_file_path:
    load_and_display_image(text_file_path)


File not found: path_to_your_image.jpg
